---
- name: update primary nameservers
  hosts: primaries
  remote_user: keith
  become: true
  gather_facts: true
  roles:
    - common
    - primary

- name: update secondary nameservers
  hosts: secondaries
  remote_user: keith
  become: true
  gather_facts: true
  roles:
    - common
    - secondary
