---
- name: update zones
  hosts: primaries
  remote_user: keith
  become: true
  gather_facts: true

  vars:
    nsd_dir: /usr/local/etc/nsd
    spf: "v=spf1 ip4:5.9.82.71 ip6:2a01:4f8:162:4e::1:1 a mx -all"
    mailserver: mail.talideon.com
    haddrs:
      cian:
        ipv4: 45.55.149.240
        ipv6: 2604:a880:800:10::716:6001
      manann:
        ipv4: 5.9.82.71
        ipv6: 2a01:4f8:162:4e::1:1
      statler: # statler.moybella.net
        ipv4: 37.187.57.205
        ipv6: 2001:41d0:b:5cd::205
        tsig: cian-key.
      blacknight: # ns2.blacknightsolutions.com
        ipv4: 78.153.202.4
        ipv6: 2a01:a8:dc2:33::33
    hroles:
      web: cian
      mail: cian
    zones:
      - canthack.it
      - gaughan.me
      - ismulleyonatrain.com
      - keithgaughan.ie
      - roguebeauty.org
      - stereochro.me
      - talideon.com
      - talideon.eu
      - tripletrek.com
      - wafflecopter.net
      - xn--cat-rma.eu
    mail_zones:
      - gaughan.me
      - roguebeauty.org
      - talideon.eu
      - tripletrek.com
    zone_cnames:
      canthack.it:
        - i
    secondary_patterns:
      slave_niallk:
        ipv4: 81.17.243.32 # Or: 185.2.64.125
        tsig: cia.niley.net
    secondary_zones:
      nk.ie: slave_niallk
      niley.net: slave_niallk
      nil.ie: slave_niallk

  tasks:
    - name: include the vault file
      include_vars:
        file: keys.yml

    # We assume that nsd is installed and nsd-control is configured.
    # Also /keys.conf and /nsd.conf
    - name: ensure zones directory exists
      file:
        path: "{{ nsd_dir }}/zones"
        state: directory
        owner: nsd
        group: nsd
        mode: 0755

    - include: templating.yml
      with_items: '{{ zones }}'

    - name: generate keys.conf
      template:
        src: keys.conf.j2
        dest: "{{ nsd_dir }}/keys.conf"
        owner: nsd
        group: nsd
        mode: 0600
      notify:
        - reload nsd

    - name: generate zones.conf
      template:
        src: zones.conf.j2
        dest: "{{ nsd_dir }}/zones.conf"
        owner: nsd
        group: nsd
        mode: 0644
      notify:
        - reload nsd

  handlers:
    - name: reload nsd
      service:
        name: nsd
        state: reloaded
