---
- name: update zones
  hosts: primaries
  remote_user: keith
  become: true
  gather_facts: true

  vars:
    nsd_dir: /usr/local/etc/nsd
    spf: "v=spf1 ip4:5.9.82.71 ip6:2a01:4f8:162:4e::1:1 a mx -all"
    mailserver: mail.talideon.com
    haddrs:
      lir:  # My Blacknight box.
        ipv4: 78.153.202.217
        ipv6: 2a01:a8:201::217
      cian:  # My Digital Ocean VM.
        ipv4: 45.55.149.240
        ipv6: 2604:a880:800:10::716:6001
      manann:  # My Hetzner box.
        ipv4: 5.9.82.71
        ipv6: 2a01:4f8:162:4e::1:1
      blacknight: # ns2.blacknightsolutions.com
        ipv4: 78.153.202.4
        ipv6: 2a01:a8:dc2:33::33
    hroles:
      web: cian
      mail: cian
    zones:
      - canthack.it
      - gaughan.me
      - ismulleyonatrain.com
      - keithgaughan.ie
      - roguebeauty.org
      - stereochro.me
      - talideon.com
      - talideon.eu
      - tripletrek.com
      - wafflecopter.net
      - xn--cat-rma.eu
    mail_zones:
      - gaughan.me
      - roguebeauty.org
      - talideon.eu
      - tripletrek.com
    zone_cnames:
      canthack.it:
        - i
      talideon.com:
        - www
        - repos
        - projects
        - reader
        - bethisad
        - mirrors
    secondary_patterns:
      slave_niallk:
        ipv4: 185.2.64.125 # 46.22.136.104
        tsig: cia.niley.net
    secondary_zones:
      nk.ie: slave_niallk
      niley.net: slave_niallk
      nil.ie: slave_niallk

  tasks:
    - name: include the vault file
      include_vars:
        file: keys.yml

    # We assume that nsd is installed and nsd-control is configured.
    # Also /keys.conf and /nsd.conf
    - name: ensure zones directory exists
      file:
        path: "{{ nsd_dir }}/zones"
        state: directory
        owner: nsd
        group: nsd
        mode: 0755

    - include: templating.yml
      with_items: '{{ zones }}'

    - name: generate keys.conf
      template:
        src: keys.conf.j2
        dest: "{{ nsd_dir }}/keys.conf"
        owner: nsd
        group: nsd
        mode: 0600
      notify:
        - reload nsd

    - name: generate zones.conf
      template:
        src: zones.conf.j2
        dest: "{{ nsd_dir }}/zones.conf"
        owner: nsd
        group: nsd
        mode: 0644
      notify:
        - reload nsd

  handlers:
    - name: reload nsd
      service:
        name: nsd
        state: reloaded
