---
- name: generate custom zone file for talideon.com
  template:
    src: "talideon.com.zone.j2"
    dest: '{{ nsd_dir }}/zones/talideon.com.zone'
  notify:
    - reload nsd
    - reload zones

- name: generate basic zone files
  template:
    src: basic.zone.j2
    dest: '{{ nsd_dir }}/zones/{{ item }}.zone'
  with_items: '{{ zones }}'
  notify:
    - reload nsd
    - reload zones

- name: generate primary zones.conf
  template:
    src: zones.conf.j2
    dest: "{{ nsd_dir }}/zones.conf"
    owner: nsd
    group: nsd
    mode: 0644
  notify:
    - reload nsd
