---
nsd_dir: /usr/local/etc/nsd
spf: "v=spf1 ip4:5.9.82.71 ip6:2a01:4f8:162:4e::1:1 a mx -all"
mailserver: mail.talideon.com
haddrs:
  lir.talideon.com:  # My Blacknight box.
    ipv4: 78.153.202.217
    ipv6: 2a01:a8:201::217
    tsig: 481d6d76-d2bf-4c4c-9384-4d98851ab1b1.talideon.com.
  cian.talideon.com:  # My Digital Ocean VM.
    ipv4: 45.55.149.240
    ipv6: 2604:a880:800:10::716:6001
    tsig: 481d6d76-d2bf-4c4c-9384-4d98851ab1b1.talideon.com.
  manann.talideon.com:  # My Hetzner box.
    ipv4: 5.9.82.71
    ipv6: 2a01:4f8:162:4e::1:1
    tsig: 481d6d76-d2bf-4c4c-9384-4d98851ab1b1.talideon.com.
  eimhir.talideon.com:  # My replacement for cian.
    ipv4: 159.203.59.98
    ipv6: 2604:a880:cad:d0::c6a:a001
    tsig: 481d6d76-d2bf-4c4c-9384-4d98851ab1b1.talideon.com.
  ns2.blacknightsolutions.com:
    ipv4: 78.153.202.4
    ipv6: 2a01:a8:dc2:33::33
hroles:
  web: cian.talideon.com
  mail: cian.talideon.com
zones:
  - canthack.it
  - gaughan.ie
  - gaughan.me
  - ismulleyonatrain.com
  - keithgaughan.ie
  - roguebeauty.org
  - stereochro.me
  - talideon.com
  - talideon.eu
  - tripletrek.com
  - wafflecopter.net
  - xn--cat-rma.eu
mail_zones:
  - gaughan.ie
zone_cnames:
  canthack.it:
    i: "@"
  talideon.com:
    bethisad: "@"
    mirrors: "@"
    reader: eimhir
    webmail: eimhir
secondary_patterns:
  slave_niallk:
    ipv4: 185.2.64.125 # 46.22.136.104
    tsig: cia.niley.net
secondary_zones:
  nk.ie: slave_niallk
  niley.net: slave_niallk
  nil.ie: slave_niallk
